[package]
name = "cargo-liner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "~4.0", features = ["derive"] }
serde = { version = "~1.0", features = ["derive"] }
toml = "~0.5"
anyhow = "~1.0"
home = "~0.5"
